-- Enable Extensions
create extension if not exists "uuid-ossp";

-- 1. USER PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  full_name text,
  phone text,
  role text default 'user' check (role in ('user', 'admin')),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. BANNERS/ANNOUNCEMENTS TABLE
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  link_url text,
  active boolean default true,
  display_order integer default 0,
  background_color text default '#FF6B6B',
  text_color text default '#FFFFFF',
  start_date timestamp with time zone,
  end_date timestamp with time zone
);

-- 3. PRODUCTS TABLE
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text,
  image_url text,
  stock integer default 0,
  active boolean default true
);

-- 4. PROMOTIONS TABLE
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  discount_percent numeric,
  image_url text,
  active boolean default true,
  valid_until timestamp with time zone
);

-- 5. ORDERS TABLE
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users,
  customer_name text,
  customer_email text,
  customer_phone text,
  total numeric not null,
  status text default 'pending',
  items jsonb,
  invoice_type text default 'boleta',
  ruc_dni text,
  company_name text,
  delivery_address text,
  delivery_fee numeric default 0
);

-- 6. REVIEWS TABLE
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  user_name text,
  user_avatar text,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  product_id bigint references public.products(id) on delete cascade
);

-- 7. CONTACT MESSAGES
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  subject text,
  message text,
  read boolean default false
);

-- ANALYTICS TABLE (Missing in previous version)
create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  date date default CURRENT_DATE unique,
  page_views integer default 0,
  orders_count integer default 0,
  total_revenue numeric default 0
);

-- SECURITY POLICIES (Idempotent)

do $$
begin
    -- Profiles
    alter table public.profiles enable row level security;
    if not exists (select 1 from pg_policies where policyname = 'Public profiles are viewable by everyone') then
        create policy "Public profiles are viewable by everyone" on profiles for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Users can insert own profile') then
        create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Users can update own profile') then
        create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
    end if;

    -- Banners
    alter table public.banners enable row level security;
    if not exists (select 1 from pg_policies where policyname = 'Banners viewable by all') then
        create policy "Banners viewable by all" on banners for select using (active = true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Admins can manage banners') then
        create policy "Admins can manage banners" on banners for all using (
          exists (select 1 from profiles where id = auth.uid() and role = 'admin')
        );
    end if;

    -- Products
    alter table public.products enable row level security;
    if not exists (select 1 from pg_policies where policyname = 'Products viewable by all') then
        create policy "Products viewable by all" on products for select using (true);
    end if;
    if not exists (select 1 from pg_policies where policyname = 'Admins can manage products') then
        create policy "Admins can manage products" on products for all using (
          exists (select 1 from profiles where id = auth.uid() and role = 'admin')
        );
    end if;

end $$;

-- REALTIME
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table products, orders, promotions, reviews, banners, profiles;
commit;

-- FUNCTION: Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (
    new.id,
    new.email,
    case 
      when new.email = 'leninzumaran0@gmail.com' then 'admin'
      else 'user'
    end
  ) on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- TRIGGER: Create profile on user signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
