-- Enable Row Level Security (RLS)
alter default privileges in schema public grant all on tables to postgres, anon, service_role;

-- 1. Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null,
  image_url text, -- URL to Supabase Storage or external
  stock integer default 0,
  active boolean default true
);

-- 2. Create Sales/Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  total_amount numeric not null,
  status text default 'pending', -- pending, paid, delivered, cancelled
  items jsonb not null, -- Store items as JSON for simplicity: [{product_id, quantity, price}]
  shipping_address text,
  contact_phone text
);

-- 3. Create Profiles Table (to store extra user info locally if needed)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin'))
);

-- Set up RLS (Security Policies)

-- PRODUCTS: Read access for everyone, Write access for admins only
alter table public.products enable row level security;

create policy "Products are viewable by everyone"
  on products for select
  using ( true );

create policy "Admins can insert products"
  on products for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Admins can update products"
  on products for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- ORDERS: Users can see their own orders, Admins can see all
alter table public.orders enable row level security;

create policy "Users can view own orders"
  on orders for select
  using ( auth.uid() = user_id );

create policy "Admins can view all orders"
  on orders for select
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Users can create orders"
  on orders for insert
  with check ( auth.uid() = user_id );

-- PROFILES: Public read, User update own
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup (Trigger)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  return new;
end;
$$;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed some initial data
insert into public.products (name, category, price, description, image_url, stock) values
('Vodka Absolut Blue', 'VODKA', 55.00, 'Vodka sueco original, sabor puro y suave.', 'https://images.unsplash.com/photo-1618174542385-d601b6a12b18?auto=format&fit=crop&q=80&w=1000', 50),
('Ron Cartavio Black', 'RON', 28.00, 'Ron oscuro peruano ideal para cocteles.', 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?auto=format&fit=crop&q=80&w=1000', 100),
('Johnnie Walker Red Label', 'WHISKY', 65.00, 'Whisky escocés de mezcla, versátil y carácter.', 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&q=80&w=1000', 40),
('Cerveza Corona Extra', 'CERVEZA', 7.50, 'Cerveza mexicana tipo pale lager.', 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=1000', 200);
