-- Enable Row Level Security (RLS)
alter default privileges in schema public grant all on tables to postgres, anon, service_role;

-- 1. Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null,
  image_url text,
  stock integer default 0,
  active boolean default true,
  wholesale_price numeric,
  wholesale_min integer default 12
);

-- 2. Create Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  total_amount numeric not null,
  status text default 'pending',
  items jsonb not null,
  shipping_address text,
  contact_phone text,
  delivery_fee numeric default 0,
  distance_km numeric default 0
);

-- 3. Create Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin'))
);

-- 4. Create Analytics Table
create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  date date default current_date,
  page_views integer default 0,
  unique_visitors integer default 0
);

-- Realtime publication
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table products, orders;
commit;

-- Security Policies
alter table public.products enable row level security;
create policy "Products are viewable by everyone" on products for select using ( true );
create policy "Admins can insert products" on products for insert with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );
create policy "Admins can update products" on products for update using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );
create policy "Admins can delete products" on products for delete using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

alter table public.orders enable row level security;
create policy "Users can view own orders" on orders for select using ( auth.uid() = user_id );
create policy "Admins can view all orders" on orders for select using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );
create policy "Users can create orders" on orders for insert with check ( auth.uid() = user_id );

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone" on profiles for select using ( true );
create policy "Users can insert their own profile" on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );

alter table public.analytics enable row level security;
create policy "Analytics viewable by admin" on analytics for select using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );
create policy "Anyone can insert analytics" on analytics for insert with check ( true );
create policy "Anyone can update analytics" on analytics for update using ( true );

-- Trigger for New Users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  user_role text;
begin
  if new.email = 'leninzumaran0@gmail.com' then
    user_role := 'admin';
  else
    user_role := 'user';
  end if;

  insert into public.profiles (id, full_name, avatar_url, username, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email, user_role);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed Data (Liquors for Trujillo)
insert into public.products (name, category, price, description, image_url, stock, wholesale_price, wholesale_min)
select 'Johnnie Walker Black Label', 'WHISKY', 145.00, 'Whisky escocés de 12 años, un clásico premium.', 'https://images.unsplash.com/photo-1527281032555-60dec035c93f?auto=format&fit=crop&q=80&w=800', 24, 130.00, 6
where not exists (select 1 from products where name = 'Johnnie Walker Black Label');

insert into public.products (name, category, price, description, image_url, stock, wholesale_price, wholesale_min)
select 'Ron Zacapa 23', 'RON', 220.00, 'Ron guatemalteco añejado en las nubes, suavidad extrema.', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800', 12, 205.00, 3
where not exists (select 1 from products where name = 'Ron Zacapa 23');
