-- 1. Create table for store settings if it doesn't exist
CREATE TABLE IF NOT EXISTS public.store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on RLS for store_settings
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Handle policies safely (Drop first to avoid "already exists" error)
DROP POLICY IF EXISTS "Allow public read access" ON public.store_settings;
CREATE POLICY "Allow public read access" ON public.store_settings
    FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow admin insert/update" ON public.store_settings;
CREATE POLICY "Allow admin insert/update" ON public.store_settings
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Insert default values for store_settings
INSERT INTO public.store_settings (key, value) VALUES
('store_address', 'Mercado La Hermelinda'),
('store_hours', '8:00 AM - 4:00 PM')
ON CONFLICT (key) DO NOTHING;

-- 2. Add missing columns to ORDERS table
DO $$
BEGIN
    -- Add delivery_time
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'delivery_time') THEN
        ALTER TABLE public.orders ADD COLUMN delivery_time TEXT;
    END IF;

    -- Add invoice_type (Boleta/Factura)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'invoice_type') THEN
        ALTER TABLE public.orders ADD COLUMN invoice_type TEXT DEFAULT 'boleta';
    END IF;

    -- Add ruc_dni
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'ruc_dni') THEN
        ALTER TABLE public.orders ADD COLUMN ruc_dni TEXT;
    END IF;

    -- Add company_name (Reason Social)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'company_name') THEN
        ALTER TABLE public.orders ADD COLUMN company_name TEXT;
    END IF;
END $$;

-- 3. Add wholesale columns to PRODUCTS table if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'wholesale_price') THEN
        ALTER TABLE public.products ADD COLUMN wholesale_price NUMERIC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'wholesale_min') THEN
        ALTER TABLE public.products ADD COLUMN wholesale_min INTEGER DEFAULT 12;
    END IF;
END $$;
