-- 1. Create table for store settings if it doesn't exist
CREATE TABLE IF NOT EXISTS public.store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on RLS for store_settings
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone for store_settings
CREATE POLICY "Allow public read access" ON public.store_settings
    FOR SELECT TO public USING (true);

-- Allow full access to authenticated users (admins) for store_settings
CREATE POLICY "Allow admin insert/update" ON public.store_settings
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Insert default values for store_settings
INSERT INTO public.store_settings (key, value) VALUES
('store_address', 'Mercado La Hermelinda'),
('store_hours', '8:00 AM - 4:00 PM')
ON CONFLICT (key) DO NOTHING;

-- 2. Add delivery_time column to orders table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'delivery_time') THEN
        ALTER TABLE public.orders ADD COLUMN delivery_time TEXT;
    END IF;
END $$;
